export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const OBTENER_PROYECTO_TODOS = 'OBTENER_PROYECTO_TODOS';
export const OBTENER_PROYECTO_NOMBRE = 'OBTENER_PROYECTO_NOMBRE';
export const OBTENER_PROYECTO_SELECTO = 'OBTENER_PROYECTO_SELECTO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const AGREGAR_TAREAS = 'AGREGAR_TAREAS';
export const VALIDAR_TAREAS = 'VALIDAR_TAREAS';
export const ELIMINAR_TAREAS = 'ELIMINAR_TAREAS';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const EDITAR_TAREA = 'EDITAR_TAREA';
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const OBTENER_CAPITULO = 'OBTENER_CAPITULO';
export const OBTENER_CAPITULO_ACTUAL = 'OBTENER_CAPITULO_ACTUAL';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION= 'CERRAR_SESION';
